"""
Django settings for warehouse project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*2sk08qbq3e@qud4#60jx94g@+q$=c=5w!&xt_rik(_j-vn6sb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


from pathlib import Path
from django.utils.translation import gettext_lazy as _
from decimal import Decimal




# SECURITY WARNING: keep the secret key used in production secret!



LANGUAGES = [
    ('en', _('English')),
    ('ar', _('Arabic')),
]



TIME_ZONE = "Asia/Kolkata"
LANGUAGE_CODE = 'en'

USE_I18N = True
USE_TZ = True




LOCALE_PATHS = [
    BASE_DIR / 'locale',
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'admin_app',
    'maintenance',
    'inventory_manager',
    'procurement_officer',
    'security',
    
    'quality_control',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',

    'admin_app.middleware.SimpleSessionExpiryMiddleware',
    'admin_app.middleware.AutoLogoutMiddleware',

    'warehouse.middleware.CompanyMiddleware.CompanyMiddleware',
    'warehouse.middleware.CompanyTimezoneMiddleware.CompanyTimezoneMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'admin_app.middleware.UnauthorizedAccessMiddleware',
    'maintenance.middleware.MaintenanceModeMiddleware',
]


ROOT_URLCONF = 'warehouse.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'maintenance.context_processors.maintenance_notifications',
                'admin_app.context_processors.settings_processor',
                "admin_app.context_processors.admin_unread_notifications",
                'admin_app.context_processors.session_warning',
                'admin_app.context_processors.current_time_processor',

            ],
        },
    },
]

WSGI_APPLICATION = 'warehouse.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {

    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
    
    "INDIA001": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "comp_a.sqlite3",
    },
    "DUBAI001": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "comp_b.sqlite3",
    },
    "MUSCAT001": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "comp_c.sqlite3",},

    
}


DATABASE_ROUTERS = [
    "warehouse.db_router.CompanyDBRouter",

]

TESSERACT_CMD = os.getenv(
    "TESSERACT_CMD",
    r"C:\Program Files\Tesseract-OCR\tesseract.exe"
)

DEFAULT_COMPANY_TIMEZONE = "Asia/Kolkata"

# Auto-generate timezone map for every database
COMPANY_TIMEZONES = {
    db_name: DEFAULT_COMPANY_TIMEZONE
    for db_name in DATABASES.keys()
}

# Override specific ones
COMPANY_TIMEZONES.update({
    "DUBAI001": "Asia/Dubai",
    "MUSCAT001": "Asia/Muscat",

})

LANGUAGE_OPTIONS = {
    "INDIA001": [],
    "DUBAI001": ["en", "ar"],
    "MUSCAT001": ["en", "ar"],
    "SAUDI001": ["en", "ar"],
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/





# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# For normal users
LOGIN_URL = '/en/user-login/'

# Optional: After login, redirect
LOGIN_REDIRECT_URL = '/en/dashboard/'  # or whichever default dashboard


# settings.py

# Set session age in seconds (e.g., 30 minutes = 1800 seconds)
SESSION_COOKIE_AGE = 300 # 5 hours  

# Reset session expiry on every request (optional, useful for active users)
SESSION_SAVE_EVERY_REQUEST = True

# Use browser-length sessions (optional)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'ibinibenny066@gmail.com'
EMAIL_HOST_PASSWORD = 'goqh bfoc zjmq xpxw'  # Use App Password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

ADMIN_SECURITY_KEY = "codedu"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}
