# Generated by Django 5.2 on 2025-10-16 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('WAREHOUSE_MANAGER', 'Warehouse Manager'), ('INVENTORY_SUPERVISOR', 'Inventory Supervisor'), ('STOREKEEPER', 'Storekeeper'), ('LOGISTICS', 'Logistics/Delivery Staff'), ('FINANCE', 'Finance/Accounts'), ('EXTERNAL', 'External User (Vendor/Client)')], max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
