# Generated by Django 5.2.5 on 2025-10-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
