# Generated by Django 5.2.5 on 2025-10-17 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_adminprofile_otp_alter_adminprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='resume',
        ),
    ]
