# Generated by Django 5.2.5 on 2025-10-30 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('WAREHOUSE_MANAGER', 'Warehouse Manager'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('STOREKEEPER', 'Storekeeper'), ('LOGISTICS', 'Logistics/Delivery Staff'), ('FINANCE', 'Finance/Accounts'), ('EXTERNAL', 'External User (Vendor/Client)'), ('PROCUREMENT_OFFICER', 'Procurement Officer'), ('SUPPLIER', 'Supplier'), ('DELIVERY_BOY', 'Delivery Boy')], max_length=50),
        ),
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ON_LEAVE', 'On Leave')], default='ACTIVE', max_length=20)),
                ('assigned_area', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_boy_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
