# Generated by Django 5.2.5 on 2025-10-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_remove_supplier_email_remove_supplier_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('WAREHOUSE_MANAGER', 'Warehouse Manager'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('STOREKEEPER', 'Storekeeper'), ('LOGISTICS', 'Logistics/Delivery Staff'), ('FINANCE', 'Finance/Accounts'), ('EXTERNAL', 'External User (Vendor/Client)'), ('PROCUREMENT_OFFICER', 'Procurement Officer'), ('SUPPLIER', 'Supplier'), ('SALES_OFFICER', 'Sales Officer'), ('DELIVERY_BOY', 'Delivery Boy')], max_length=50),
        ),
    ]
