# Generated by Django 5.2.7 on 2025-11-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
