# Generated by Django 5.2 on 2025-11-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0016_supplier_supplier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='last_otp_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
