# Generated by Django 5.2 on 2025-11-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_adminprofile_last_otp_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='last_otp_verified',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='blocked_for_reset',
            field=models.BooleanField(default=False),
        ),
    ]
