# Generated by Django 5.2 on 2025-11-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0018_remove_adminprofile_last_otp_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='blocked_for_reset',
        ),
    ]
