# Generated by Django 5.2 on 2025-11-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0020_userprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
