# Generated by Django 5.2 on 2025-11-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0022_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='last_otp_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
