# Generated by Django 5.2 on 2025-11-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0024_function_role_rolefunction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolefunction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rolefunction',
            name='functions',
            field=models.ManyToManyField(to='admin_app.function'),
        ),
        migrations.AlterField(
            model_name='rolefunction',
            name='role',
            field=models.CharField(choices=[('WAREHOUSE_MANAGER', 'Warehouse Manager'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('STOREKEEPER', 'Storekeeper'), ('LOGISTICS', 'Logistics/Delivery Staff'), ('FINANCE', 'Finance/Accounts'), ('EXTERNAL', 'External User (Vendor/Client)'), ('PROCUREMENT_OFFICER', 'Procurement Officer'), ('SUPPLIER', 'Supplier'), ('SALES_OFFICER', 'Sales Officer'), ('DELIVERY_BOY', 'Delivery Boy')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='rolefunction',
            name='function',
        ),
    ]
