# Generated by Django 5.2.5 on 2025-12-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0026_alter_rolefunction_role_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
            ],
        ),
    ]
