# Generated by Django 5.2 on 2025-12-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0027_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolefunction',
            name='role',
            field=models.CharField(choices=[('WAREHOUSE_MANAGER', 'Warehouse Manager'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('STOREKEEPER', 'Storekeeper'), ('LOGISTICS', 'Logistics/Delivery Staff'), ('FINANCE', 'Finance/Accounts'), ('EXTERNAL', 'External User (Vendor/Client)'), ('PROCUREMENT_OFFICER', 'Procurement Officer'), ('SUPPLIER', 'Supplier'), ('SALES_OFFICER', 'Sales Officer'), ('DELIVERY_BOY', 'Delivery Boy'), ('MAINTENANCE_STAFF', 'Maintenance Staff'), ('SECURITY', 'Security')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('WAREHOUSE_MANAGER', 'Warehouse Manager'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('STOREKEEPER', 'Storekeeper'), ('LOGISTICS', 'Logistics/Delivery Staff'), ('FINANCE', 'Finance/Accounts'), ('EXTERNAL', 'External User (Vendor/Client)'), ('PROCUREMENT_OFFICER', 'Procurement Officer'), ('SUPPLIER', 'Supplier'), ('SALES_OFFICER', 'Sales Officer'), ('DELIVERY_BOY', 'Delivery Boy'), ('MAINTENANCE_STAFF', 'Maintenance Staff'), ('SECURITY', 'Security')], max_length=50),
        ),
    ]
