# Generated by Django 5.2 on 2025-12-27 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0030_alter_rolefunction_role_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('Picking', 'Picking'), ('Dispatch', 'Dispatch'), ('SalesOrder', 'SalesOrder'), ('Packing', 'Packing'), ('Delivery', 'Delivery'), ('Purchase', 'Purchase'), ('Batch', 'Batch'), ('Salesinvoice', 'Salesinvoice'), ('Purchaseinvoice', 'Purchaseinvoice'), ('Stock', 'Stock')], max_length=50)),
                ('file', models.FileField(max_length=500, upload_to='reports/%Y/%m/')),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
