# Generated by Django 5.2 on 2026-01-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0031_reportfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Database alias like INDIA001, DUBAI001', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
