# Generated by Django 5.2 on 2026-01-06 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0032_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.warehouse'),
        ),
    ]
