# Generated by Django 5.2.7 on 2026-01-28 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0034_usersessiontimer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
