# Generated by Django 5.2.5 on 2026-02-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0012_bin_barcode_image_bin_location_code_bin_rack_and_more'),
        ('procurement_officer', '0002_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='category_variant',
            field=models.ManyToManyField(blank=True, to='inventory_manager.categoryvariant'),
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product_variant',
            field=models.ManyToManyField(blank=True, to='inventory_manager.productvariantvalue'),
        ),
    ]
