# Generated by Django 5.2.7 on 2026-01-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcinspection',
            name='po_item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
