# Generated by Django 5.2.7 on 2026-01-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0002_alter_qcinspection_po_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcchecklistitem',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('FOOD', 'Food'), ('MEDICAL', 'Medical'), ('CLOTHING', 'Clothing')], default='ELECTRONICS', max_length=20),
            preserve_default=False,
        ),
    ]
