# Generated by Django 5.2.7 on 2026-01-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0003_qcchecklistitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcinspection',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Mandatory for FOOD / MEDICAL', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='category',
            field=models.CharField(default='ELECTRONICS', help_text='ELECTRONICS / FOOD / MEDICAL / CLOTHING', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Mandatory for FOOD / MEDICAL', null=True),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
