# Generated by Django 5.2.7 on 2026-01-23 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0004_qcinspection_batch_number_qcinspection_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QCChecklistResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pass', models.BooleanField(null=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_control.qcchecklist')),
                ('qc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_results', to='quality_control.qcinspection')),
            ],
        ),
    ]
