# Generated by Django 5.2.7 on 2026-01-23 08:30

import quality_control.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0005_qcchecklist_qcchecklistresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qcchecklistresult',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='qcchecklistresult',
            name='qc',
        ),
        migrations.RemoveField(
            model_name='qcinspectionphoto',
            name='inspection',
        ),
        migrations.AddField(
            model_name='qcinspectionanswer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=quality_control.models.qc_photo_path),
        ),
        migrations.AddField(
            model_name='qcinspectionanswer',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='QCChecklist',
        ),
        migrations.DeleteModel(
            name='QCChecklistResult',
        ),
        migrations.DeleteModel(
            name='QCInspectionPhoto',
        ),
    ]
