# Generated by Django 5.2.7 on 2026-01-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0007_alter_qcinspection_inspector'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcchecklistitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qcchecklistitem',
            name='inspection_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qcchecklistitem',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='qc_checklist/'),
        ),
    ]
