# Generated by Django 5.2.7 on 2026-01-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0008_qcchecklistitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcchecklistitem',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('FOOD', 'Food'), ('MEDICAL', 'Medical'), ('CLOTHING', 'Clothing'), ('CHEMICAL', 'Chemical')], max_length=20),
        ),
    ]
