# Generated by Django 5.2.7 on 2026-01-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0009_alter_qcchecklistitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcchecklistitem',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('FOOD', 'Food'), ('MEDICAL', 'Medical'), ('CLOTHING', 'Clothing'), ('CHEMICALS', 'Chemicals')], max_length=20),
        ),
        migrations.AlterField(
            model_name='qcinspection',
            name='category',
            field=models.CharField(help_text='ELECTRONICS / FOOD / MEDICAL / CLOTHING /CHEMICALS', max_length=50),
        ),
    ]
