# Generated by Django 5.2.7 on 2026-01-31 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0010_alter_qcchecklistitem_category_and_more'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcinspection',
            name='security_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qc_inspections', to='security.securitypoinvoice'),
        ),
    ]
