# Generated by Django 5.2.7 on 2026-01-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0011_qcinspection_security_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcinspection',
            name='pdf_processed',
            field=models.BooleanField(default=False),
        ),
    ]
