# Generated by Django 5.2.7 on 2026-01-30 09:51

import django.db.models.deletion
import security.Utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPOInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=30)),
                ('vendor_name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('uploaded_invoice', models.FileField(upload_to=security.Utils.po_invoice_upload_path)),
                ('system_verified', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_name', models.CharField(max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=50)),
                ('front_image', models.ImageField(blank=True, null=True, upload_to=security.Utils.vehicle_entry_image_path)),
                ('rear_image', models.ImageField(blank=True, null=True, upload_to=security.Utils.vehicle_entry_image_path)),
                ('side_image', models.ImageField(blank=True, null=True, upload_to=security.Utils.vehicle_entry_image_path)),
                ('driver_image', models.ImageField(blank=True, null=True, upload_to=security.Utils.vehicle_entry_image_path)),
                ('gate_no', models.CharField(max_length=10)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='security/barcodes/')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('po_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_entries', to='security.securitypoinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_qty', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('front_image', models.ImageField(upload_to=security.Utils.vehicle_exit_image_path)),
                ('rear_image', models.ImageField(upload_to=security.Utils.vehicle_exit_image_path)),
                ('side_image', models.ImageField(upload_to=security.Utils.vehicle_exit_image_path)),
                ('exit_time', models.DateTimeField(auto_now_add=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleexit', to='security.vehicleentry')),
            ],
        ),
    ]
