# Generated by Django 5.2.7 on 2026-01-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitypoinvoice',
            name='category',
            field=models.CharField(blank=True, choices=[('FOOD', 'Food'), ('CHEMICALS', 'Chemicals'), ('MEDICAL', 'Medical'), ('ELECTRONICS', 'Electronics'), ('CLOTHING', 'Clothing')], max_length=20, null=True),
        ),
    ]
