# Generated by Django 5.2.7 on 2026-01-20 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0033_userprofile_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_manager.rack')),
            ],
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_number', models.CharField(max_length=10)),
                ('capacity', models.IntegerField(default=100)),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_manager.shelf')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='rack',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_manager.zone'),
        ),
    ]
