# Generated by Django 5.2.7 on 2026-01-21 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_serialized', models.BooleanField(default=False)),
                ('is_lotted', models.BooleanField(default=True)),
                ('shelf_type_required', models.CharField(choices=[('PALLET', 'Pallet'), ('RACK', 'Rack'), ('BIN', 'Bin')], default='RACK', max_length=30)),
                ('fifo_fefo', models.CharField(choices=[('FIFO', 'FIFO'), ('FEFO', 'FEFO')], default='FIFO', max_length=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_manager.productcategory')),
            ],
        ),
    ]
