# Generated by Django 5.2.7 on 2026-01-21 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0004_alter_productvariant_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=4554, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CategoryVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_type', models.CharField(max_length=50)),
                ('variant_value', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory_manager.productcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
