# Generated by Django 5.2.7 on 2026-01-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0005_product_unit_price_categoryvariant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_serialized',
            new_name='expiry_required',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_lotted',
        ),
        migrations.AddField(
            model_name='product',
            name='max_shelf_life_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='has_variants',
            field=models.BooleanField(default=False),
        ),
    ]
