# Generated by Django 5.2.7 on 2026-01-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0006_rename_is_serialized_product_expiry_required_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='max_shelf_life_days',
            new_name='default_expiry_days',
        ),
        migrations.AddField(
            model_name='product',
            name='default_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
