# Generated by Django 5.2.7 on 2026-01-21 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0007_rename_max_shelf_life_days_product_default_expiry_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_manager.categoryvariant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='inventory_manager.product')),
            ],
        ),
    ]
