# Generated by Django 5.2.7 on 2026-01-21 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0008_productvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_manager.categoryvariant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_prices', to='inventory_manager.product')),
            ],
            options={
                'unique_together': {('product', 'category_variant')},
            },
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
