# Generated by Django 5.2.7 on 2026-01-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0009_productvariantprice_delete_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='warehouse',
        ),
    ]
