# Generated by Django 5.2.7 on 2026-01-27 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0010_remove_zone_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('has_expiry', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='default_expiry_date',
            new_name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='categoryvariant',
            name='variant_type',
        ),
        migrations.RemoveField(
            model_name='categoryvariant',
            name='variant_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='default_expiry_days',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='expiry_required',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fifo_fefo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shelf_type_required',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='categoryvariant',
            name='name',
            field=models.CharField(default='Default Variant', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='categoryvariant',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory_manager.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_manager.category'),
        ),
        migrations.CreateModel(
            name='ProductVariantValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_values', to='inventory_manager.product')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_manager.categoryvariant')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductVariantPrice',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
