# Generated by Django 5.2.7 on 2026-01-29 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0011_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='location_barcodes/'),
        ),
        migrations.AddField(
            model_name='bin',
            name='location_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bin',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_manager.rack'),
        ),
        migrations.AddField(
            model_name='bin',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_manager.zone'),
        ),
        migrations.AlterField(
            model_name='bin',
            name='bin_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bin',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_manager.shelf'),
        ),
        migrations.AlterField(
            model_name='categoryvariant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rack',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_manager.zone'),
        ),
    ]
